### ISSUE TITLE
equivalent of "up" "down" ?

### ISSUE THREAD

**Issue by jayunit100** [openshift/vagrant-openshift#420]
assuming that sync-origin is meant to bring up a fully working openshift cluster based on  @danmcp feedback in IRC....

the bug i am seeing  is as follows... 

```
  vagrant build-origin
  vagrant sync-origin
  vagrant try-restart-origin
```
the ensuing cluster has an empty config file.
```
[root@localhost vagrant]# cat /openshift.local.config/master/admin.kubeconfig
[root@localhost vagrant]#
```
maybe this is not a bug, 
- if not - how do i bring up a working cluster w/ nonempty kubeconfigs and a node+master running, using the plugin ? 
- In any case, I can't oc login b/c it thinks the config is empty, (another issue, is openshift reports this as no file found which ive created a pr to fix https://github.com/openshift/origin/pull/7837) 

I'd say we can close this issue ønce "vagrant" shows a plugin option which decribes something similar to `kube up`.  I'm pretty sure we support such an option, just not sure what it is...

**Comment by danmcp** [comment]
@jayunit100 I don't think any of the commands you ran actually started openshift.  You could run:

vagrant ssh -c "sudo systemctl start openshift"

**Comment by jayunit100** [comment]
@danmcp  - should we simply have a "vagrant-openshift up" similar to the upstream kube-up ?  cc @smarterclayton .

**Comment by danmcp** [comment]
@jayunit100 The issue is that the devenvs are used for 2 purposes (development and testing).  If you use them for development, you don't want the services started because they conflict with running tests.  If you use them for testing you do want them started.  The default OOTB is to favor the development scenario and not start everything up.  There are other VMs that exist (The CDK and the one @thesteve0 and @jwhonce created) that are meant to handle the end user scenarios.  I don't personally have any objection to making vagrant-openshift better within it's niche, but I don't want to add even another option to the list that everyone has to choose between.

**Comment by jayunit100** [comment]
hmmm ok, so, to be clear: you're saying that running an openshift cluster from source is not a use case that `vagrant-openshift` is meant to cover?

**Comment by danmcp** [comment]
@jayunit100 It's just not its primary use case.  And the more we do to make that it's use case, the more it will conflict with either the CDK or openshift-ansible.  The momentum seems to be more in the other direction of making openshift-ansible more accessible for these types of scenarios.

**Comment by smarterclayton** [comment]
Ideally in the origin repo we'd have cluster/up.sh or similar that depends
on a known commit of openshift-ansible.

**Comment by jayunit100** [comment]
Yeah, It seems to me that Such a recipe  would obviate the need for any other tooling for the majority of dev AND test use cases:.... After all, upstream kube can be entirely developed using nothing other than vim and kube-up.sh,
